spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spring_reactive
    username: postgres
    password: root
  flyway:
    user: postgres
    password: root
    enabled: true
    url: jdbc:postgresql://localhost:5432/spring_reactive

